  
 export    let data =  [
        {
            id:1,
            title:'Bullmer',
            price:'899',
            category:'Tshirt',
            description:'Tribal Printed Oversized Cotton T-shirt',
            productDetails:'Beige Tshirt for men,Tribal printed,Regular length, Round neck Short, regular sleeves, Knitted cotton fabric',
            Productimage:'https://m.media-amazon.com/images/I/71rhSWZvmHL._AC_UY1100_.jpg',
            Detailimage1:'https://m.media-amazon.com/images/I/618hKHO8QyL._SY741_.jpg',
            Detailimage2:'https://m.media-amazon.com/images/I/618hKHO8QyL._SY741_.jpg',
            rating:'4.5',
        },
        {
            id:2,
            title:'HRX by ',
            price:'349',
            category:'Tshirt',
            description:'Men Olive Green Solid Bio-Wash Running Tshirt',
            productDetails:'Cut for style and comfort, the HRX Mens Running T-shirt is great for short warm up jogs as well as long Sunday cross country running. The bio washed cotton base feels soft against your skin and is perfect for all kinds of weather.',
            Productimage:'https://thehouseofrare.com/cdn/shop/products/IMG_0053_5c650849-9d9d-4cc3-8863-6a23778cd9a0.jpg?v=1675170808',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/products/IMG_0055_3fada402-1121-45c8-bd5b-06bed1392315_765x.jpg?v=1666174660',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/products/IMG_0064_3c0ccd02-595e-4876-b444-27b33e57c0a0_765x.jpg?v=1666174582',
            rating:'4',
        }, 
        {
            id:3,
            title:'Roadster',
            price:'343',
            category:'Tshirt',
            description:'The Lifestyle Co Men Mustard Yellow Solid Round Neck Pure Cotton T-shirt',
            productDetails:'PRODUCT DETAILS ,Mustard yellow solid T-shirt with printed detail, has a round neck, and short sleeves, Size & Fit, The model (height 6) is wearing a size M, Material & Care,Material: 100% Cotton,Machine Wash',
            Productimage:'https://thehouseofrare.com/cdn/shop/files/CARMELON-PASTEL-BLUE15880_765x.jpg?v=1711433601',
            Detailimage1:'https://thehouseofrare.com/products/carmelon-mens-polo-pastel-blue',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/files/CARMELON-PASTEL-BLUE15862_765x.jpg?v=1711433601',
            rating:'4.5',
        },
        {
            id:4,
            title:'TEXTURED  SHIRT',
            price:'1539.00',
            category:'Shirt',
            description:'AFFLE - DARK PURPLE',
            productDetails:"-A classic self textured Dobby shirt. - Can be worn for from office to after meeting evening get together. -Liked by Father and Son age groups -Invisible buttoned down collar so the collars stays at place all day with ease. -100% premium Cotton with self dobby texture -Short Sleeves - Can be paired with Rare Rabbit Trouser" ,
            Productimage:'https://thehouseofrare.com/cdn/shop/products/HERO_8bcf9be4-3284-4218-9de5-e1df3ccf9624_765x.jpg?v=1708434602',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/products/IMG_0010_582497ec-9b28-4234-921a-9aab7d2e5b38_765x.jpg?v=1708434572',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/products/IMG_0003_1_2e38753e-0a29-40f6-b086-cb2130b57fd1_765x.jpg?v=1677749482',
            rating:'3.5',
        },
        {
            id:5,
            title:' CHECK SHIRT',
            price:'1899',
            category:'Shirt',
            description:'FOLEY - LIGHT BEIGE',
            productDetails:'Beige Tshirt for men,Tribal printed,Regular length, Round neck Short, regular sleeves, Knitted cotton fabric',
            Productimage:'https://thehouseofrare.com/cdn/shop/files/FOLEY-LIGHT-BEIGE-04450_765x.jpg?v=1692618199',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/files/FOLEY-LIGHT-BEIGE-04435_765x.jpg?v=1692618199',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/files/FOLEY-LIGHT-BEIGE-04430_765x.jpg?v=1692618199',
            rating:'5',
        },
        {
            id:6,
            title:'CLASSIC SHIRT',
            price:'3140',
            category:'Tshirt',
            description:'GUILD BUSINESS - COMB-1 - NAVY',
            productDetails:"-A classic self textured Dobby shirt. - Can be worn for from office to after meeting evening get together. -Liked by Father and Son age groups -Invisible buttoned down collar so the collars stays at place all day with ease. -100% premium Cotton with self dobby texture -Short Sleeves - Can be paired with Rare Rabbit Trouser" ,
            Productimage:'https://m.media-amazon.com/images/I/71rhSWZvmHL._AC_UY1100_.jpg',
            Detailimage1:'https://m.media-amazon.com/images/I/618hKHO8QyL._SY741_.jpg',
            Detailimage2:'https://m.media-amazon.com/images/I/618hKHO8QyL._SY741_.jpg',
            rating:'3.5',
        },
        {
            id:7,
            title:'STRETCH JEANS',
            price:'2500',
            category:'Jeans',
            description:'DAVID 4 - BLUE',
            productDetails:'- A slim-fit stretch denim with metal branding.- Features 5 pocket design.- Zip fly & shank button fastening.- Regular rise.- Poly Cotton Fabric',
            Productimage:'https://thehouseofrare.com/cdn/shop/products/IMG_0042_1d8c2541-e633-433f-a375-a95bb6f99eee_765x.jpg?v=1693639011',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/products/IMG_0045_8b58103b-f3e1-4072-849c-49477b2f54eb_765x.jpg?v=1693639011',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/products/IMG_0026_8998715b-143a-47e1-91d6-5030ae0e7a8d_765x.jpg?v=1693639011',
            rating:'4.5',
        },
        {
            id:8,
            title:' LIGHT JEANS',
            price:'2749.00',
            category:'Jeans',
            description:'SAM - PASTEL BLUE',
            productDetails:'Carrot-fit jeans transform the core of contemporary fashion, featuring a distinctive silhouette that gracefully narrows from the hips to the ankles, inspired by the organic nature of a carrot. Seamlessly combining avant-garde design with unmatched comfort, these jeans provide a tailored appearance coupled with a comfortably spacious fit around the hips and thighs, achieving a harmonious blend of sophistication and ease. Versatile and effortlessly stylish, they emerge as the go-to option for individuals desiring a seamless integration of cutting-edge aesthetics and unwavering comfort.',
            Productimage:'https://thehouseofrare.com/cdn/shop/files/Sam-pastel-blue-0137HERO_765x.jpg?v=1698908327',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/files/Sam-pastel-blue-0143_765x.jpg?v=1698918448',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/files/Sam-pastel-blue-0149_765x.jpg?v=1698918442',
            rating:'5',
        },
        {
            id:9,
            title:'SLIM FIT  DENIM',
            price:'3999.00',
            category:'Jeans',
            description:'MESA - GREY',
            productDetails:'Beige Tshirt for men,Tribal printed,Regular length, Round neck Short, regular sleeves, Knitted cotton fabric',
            Productimage:'https://thehouseofrare.com/cdn/shop/files/MISA-GREY00626_765x.jpg?v=1707118561',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/files/MISA-GREY00623_765x.jpg?v=1707225174',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/files/MISA-GREY00625_765x.jpg?v=1707225174',
            rating:'3.5',
        },
        {
            id:10,
            title:'Bullmer',
            price:'899',
            category:'Tshirt',
            description:'Tribal Printed Oversized Cotton T-shirt',
            productDetails:'Beige Tshirt for men,Tribal printed,Regular length, Round neck Short, regular sleeves, Knitted cotton fabric',
            Productimage:'https://m.media-amazon.com/images/I/71rhSWZvmHL._AC_UY1100_.jpg',
            Detailimage1:'https://m.media-amazon.com/images/I/618hKHO8QyL._SY741_.jpg',
            Detailimage2:'https://m.media-amazon.com/images/I/618hKHO8QyL._SY741_.jpg',
            rating:'4.5',
        },
        {
            id:11,
            title:'CHECK SHIRT',
            price:'1899',
            category:'Shirt',
            description:'FOLEY - LIGHT BEIGE',
            productDetails:'Beige Tshirt for men,Tribal printed,Regular length, Round neck Short, regular sleeves, Knitted cotton fabric',
            Productimage:'https://thehouseofrare.com/cdn/shop/files/FOLEY-LIGHT-BEIGE-04450_765x.jpg?v=1692618199',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/files/FOLEY-LIGHT-BEIGE-04435_765x.jpg?v=1692618199',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/files/FOLEY-LIGHT-BEIGE-04430_765x.jpg?v=1692618199',
            rating:'5',
        },
        {
            id:12,
            title:'STRETCH JEANS',
            price:'2500',
            category:'Jeans',
            description:'DAVID 4 - BLUE',
            productDetails:'- A slim-fit stretch denim with metal branding.- Features 5 pocket design.- Zip fly & shank button fastening.- Regular rise.- Poly Cotton Fabric',
            Productimage:'https://thehouseofrare.com/cdn/shop/products/IMG_0042_1d8c2541-e633-433f-a375-a95bb6f99eee_765x.jpg?v=1693639011',
            Detailimage1:'https://thehouseofrare.com/cdn/shop/products/IMG_0045_8b58103b-f3e1-4072-849c-49477b2f54eb_765x.jpg?v=1693639011',
            Detailimage2:'https://thehouseofrare.com/cdn/shop/products/IMG_0026_8998715b-143a-47e1-91d6-5030ae0e7a8d_765x.jpg?v=1693639011',
            rating:'4.5',
        }
    ]